name: Notify Failed

on:
  workflow_call:
    inputs:
      md_message:
        description: Markdown message
        required: true
        type: string

jobs:
  notify-failure:
    runs-on: ubuntu-latest
    steps:
      - id: tools-team-slack
        uses: slackapi/slack-github-action@91efab103c0de0a537f72a35f6b8cda0ee76bf0a
        env:
          SLACK_BOT_TOKEN: ${{ secrets.VMWARE_SLACK_BOT_TOKEN }}
        with:
          channel-id: "C4W4Q9FR9"
          payload: |
            {
              "text": "${{ inputs.md_message }}",
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": ":fail: ${{ inputs.md_message }}"
                  }
                }
              ]
            }


